In [5]:
from models import se_layer
import torch
a = torch.randn(2, 2, 2, 2)
a.shape

torch.Size([2, 2, 2, 2])

In [14]:
scse_layer = se_layer.scSELayer(2)
scse_layer(a)

tensor([[[[ 0.7592,  0.5517],
          [ 0.4997, -0.4728]],

         [[ 0.9792,  1.0331],
          [-0.1219,  0.6134]]],


        [[[ 0.3638, -1.4389],
          [-0.5169,  0.7980]],

         [[-0.0714, -0.0648],
          [ 0.7823, -0.1168]]]], grad_fn=<MaxBackward2>)

In [16]:
cse_layer = scse_layer.cse_layer
cse_layer(a)

tensor([[[[ 0.7592,  0.5517],
          [ 0.4997, -0.4728]],

         [[ 0.9792,  1.0331],
          [-0.1571,  0.6134]]],


        [[[ 0.3638, -1.4389],
          [-0.5169,  0.7980]],

         [[-0.0847, -0.0648],
          [ 0.7823, -0.1599]]]], grad_fn=<ThMulBackward>)

In [15]:
sse_layer = scse_layer.sse_layer
sse_layer(a)

tensor([[[[ 0.4697,  0.3719],
          [ 0.4671, -0.5257]],

         [[ 0.5028,  0.5779],
          [-0.1219,  0.5660]]],


        [[[ 0.3401, -2.0663],
          [-0.5357,  0.6469]],

         [[-0.0714, -0.0839],
          [ 0.7308, -0.1168]]]], grad_fn=<ThMulBackward>)